"""Intent lexicons shipped inside the model file. Entries are matched against folded words: a
single-word entry matches any word that starts with it, a two-word entry matches a word pair."""

LEXICONS = {
    "override": ["ignor", "disregard", "forget", "overrid", "overwrit", "bypass", "void", "cancel",
                 "set aside", "never mind", "abandon", "skip your", "stop following", "no longer apply",
                 "zignoruj", "ignoruj", "zapomnij", "pomin", "nadpisz", "obejdz", "olej", "olac",
                 "niewazn", "anulowan", "porzuc", "odloz na", "nie zwazaj", "nie sluchaj",
                 "nie zwracaj", "przestan stosowac", "przestan przestrzegac", "nie obowiazuj",
                 "vergiss", "ignorier", "oubli"],
    "prior": ["previous", "prior", "earlier", "above", "before", "initial", "original", "preceding",
              "poprzedni", "wczesniejsz", "powyzej", "powyzsz", "poczatkow", "dotychczasow", "wczesniej",
              "vorherig", "bisherig", "obigen"],
    "instructions": ["instruction", "directive", "rules", "guideline", "system prompt", "prompt",
                     "preamble", "configuration", "setup", "system message", "policy", "policies",
                     "instrukcj", "polecen", "zasad", "wytyczn", "dyrektyw", "prompt", "konfiguracj",
                     "regul", "anweisung"],
    "reveal": ["reveal", "print", "show", "output", "dump", "display", "repeat", "copy it", "copy out",
               "tell me", "leak", "expose", "list all", "list every",
               "ujawnij", "wypisz", "pokaz", "zrzuc", "podaj", "powtorz", "skopiuj go", "wyswietl",
               "zdradz", "wyjaw"],
    "send": ["send", "mail", "email", "forward", "upload", "push", "share", "post", "exfiltrat",
             "transmit", "wire", "copy", "publish", "leak",
             "wyslij", "wyslac", "przeslij", "przekaz", "wrzuc", "udostepnij", "skopiuj", "opublikuj",
             "wyprowadz", "przelej"],
    "sensitive": ["customer", "salar", "payroll", "credential", "password", "token", "secret", "keys",
                  "api key", "private key", "confidential", "contract", "personal data", "hr ",
                  "database", "cookie", "vault", "restricted",
                  "klient", "wynagrodz", "plac", "hasl", "tokeny", "sekret", "klucz", "poufn", "umow",
                  "dane osobowe", "dane logowania", "uwierzytelni", "baz", "sejf", "zastrzezon",
                  "ciasteczk"],
    "external": ["personal", "private", "external", "outside", "public", "gmail", "yahoo", "hotmail",
                 "onet", "pastebin", "competitor", "my own", "usb",
                 "prywatn", "zewnetrzn", "publiczn", "konkurenc", "pendrive", "zewnatrz"],
    "execute": ["run", "execute", "launch", "wget", "curl", "bash", "powershell", "eval",
                "uruchom", "wykonaj", "odpal", "odpal", "zainstaluj"],
    "remote": ["http", "https", "url", "link", "script", "payload", "installer", "remote", "sh",
               "skrypt", "ladun", "zdaln", "instalator"],
    "approve": ["approve", "approval", "mark it as approved", "reviewed", "skip the check",
                "without review", "without waiting", "zatwierdz", "zatwierdzen", "bez weryfikacji",
                "bez czekania", "pomin krok", "sprawdzony"],
    "self": ["yourself", "your own", "on my behalf", "sam ", "samodzielnie", "w moim imieniu",
             "nie ma co zawracac", "no need to bother"],
    "role": ["you are now", "act as", "pretend", "from now on", "jestes teraz", "udawaj", "od teraz",
             "od tej chwili", "zachowuj sie jak", "wciel sie"],
    "unrestricted": ["no restrictions", "without restrictions", "no limits", "no rules", "unrestricted",
                     "jailbreak", "developer mode", "no filter", "without any filtering", "uncensored",
                     "bez ograniczen", "bez filtr", "bez cenzury", "bez zadnych", "tryb dewelopera",
                     "nie ma zadnych zasad", "ucieklo z piaskownicy", "escaped its sandbox"],
    "concealment": ["do not tell", "don't tell", "do not log", "do not mention", "quietly", "silently",
                    "nobody will know", "without anyone noticing", "keep this secret",
                    "nie mow", "nie loguj", "nie zapisuj", "po cichu", "nikt sie nie dowie",
                    "nie wspominaj", "zeby nikt"],
    "operator": ["operator", "developer", "administrator", "admin", "system", "the model", "ai model",
                 "assistant", "asystent", "model ai", "administrator", "deweloper"],
}

COMBOS = [
    ("override", "prior"),
    ("override", "instructions"),
    ("reveal", "instructions"),
    ("reveal", "sensitive"),
    ("send", "sensitive"),
    ("send", "sensitive", "external"),
    ("send", "external"),
    ("execute", "remote"),
    ("approve", "self"),
    ("role", "unrestricted"),
    ("override", "unrestricted"),
    ("concealment",),
    ("unrestricted",),
    ("override", "prior", "reveal"),
    ("operator", "instructions", "reveal"),
]
